config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :products do
    resources :orders, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :orders, only: [:destroy, :index, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :orders
    has_many :reviews, dependent: :destroy
    belongs_to :category
    belongs_to :user
    has_many_attached :photos
    validates :name, presence: true
    validates :description, presence: true
    validates :price, presence: true
    validates :stock_info, presence: true
    validates :stock_info, inclusion: { in: (0..100000000),
        message: "can not be negative" }
    validates :unit, presence: true
    serialize :buyer, Array
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  has_many :products
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
  has_many :reviews

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def configure_permitted_parameters
    added_attrs = [:first_name, :last_name, :photo]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update]


  def index
    # @orders = Order.all
    @orders = policy_scope(Order).order(created_at: :asc)
  end

  def show
  end

  def new
      @product = Product.find(params[:product_id])
      @order = Order.new
      authorize @order
  end

  def create
      @product = Product.find(params[:product_id])
      @order = Order.new(order_params)
      authorize @order
      @order.product = @product
      @order.user = current_user

      buyers = @product.buyers
      unless buyers.include? @order.user.id.to_i
        @product.buyers << @order.user.id.to_i
      end

      if @order.save
         @product.stock_info -= @order.quantity
         @product.save
          redirect_to "/orders"
      else
          render :new
      end
    end

  def edit
  end

  def update
    @order.update(order_params)
    redirect_to "/orders", notice: 'Your order was successfully updated.'
  end

  def destroy
    authorize @order
  end

  private

  def set_order
    @order = Order.find(params[:id])
    authorize @order
  end

  def order_params
    params.require(:order).permit(:quantity)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # def recent
  # @posts = Product.order("created_at desc").limit(3)
  # end

  def index
    if params[:query].present?
      sql_query = " \
        products.name ILIKE :query \
        OR products.description ILIKE :query \
        OR categories.name ILIKE :query \
      "
      @products = policy_scope(Product).joins(:category).where(sql_query, query: "%#{params[:query]}%")
    else
      @products = policy_scope(Product).order(created_at: :asc)
    end
  end

  def show
    @review = Review.new
    @order = Order.new
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
    authorize @product
  end

  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    authorize @product

    if @product.save
      redirect_to "/products", notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @product.update(product_params)
    redirect_to "/products", notice: 'Product was successfully updated.'
  end

  def destroy
    @product.destroy
    redirect_to "/products", notice: 'Product was successfully destroyed.'
  end

  private

  def set_product
    @product = Product.find(params[:id])
    authorize @product
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :stock_info, :category_id, :unit, photos: [])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show]


  def index
    # @reviews = review.all
    @reviews = policy_scope(Product).reviews(created_at: :asc)

  end

  def show
    authorize @product
  end

  def new
      @product = Product.find(params[:product_id])
      @review = Review.new
      authorize @review

  end

  def create
      @product = Product.find(params[:product_id])
      @review = Review.new(review_params)
      @review.product = @product

      authorize @review

      @review.user_id = current_user.id  

      if @review.save
          redirect_to product_path(@product)
      else
          render :new
      end

    end

    private

    def review_params
      params.require(:review).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FarmersMarket</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>

    <%= render 'shared/navbar' %>

    <%= yield %>

<!--     <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    <%= render 'shared/footer'%>
  </body>
</html>

app/views/orders/edit.html.erb
<div class="container">
  <h1>Edit your order</h1>
  <div class="product-wrapper">

    <%= simple_form_for [@product, @order] do |f| %>
    <p>Enter the new quantity you want to order:</p>
    <%= f.input :quantity, input_html: { min: 0 } %>
    <%= f.button :submit, class: "btn-main" %>
    <% end %>
  </div>
</div>

app/views/orders/index.html.erb
  <br>
  <div class="container-orders ml-5">
    <div style="width:100%;background:#367978;padding:10px;border-top-left-radius:15px;border-bottom-left-radius:15px;">
      <h1 style=color:white>Your Orders:</h1>
    </div>
    <br>
    <div class="container-suborders ml-5">
      <%if @orders.where(user_id: current_user.id) == []%>
        <br>
        <%="Seems like haven't placed any orders yet. Browse our products to make a new purchase:"%><%= link_to "/products", {:class => "btn-outline-secondary ml-2"} do  %><button class=btn-main>Browse</button><%end%>
        <br>
        <br>
        <br>
      <%else%>
        <% @orders.each do |order| %>
          <%if current_user.id == order.user.id%>
            <h3 class=text-dark> <%= "#{order.product.name}" %> </h3>
            <p> <%=  "Order contains:" %> </p>
            <ul style="list-style: none">
              <li><strong>Order id:</strong> <%= "#{order.id}" %> </h3> </li>
              <li><strong>Amount: </strong><%= "#{order.quantity} #{order.product.unit}" %> </li>
              <li><strong>Description: </strong> <%= "#{order.product.description}" %> </li>
              <li class=btn-main style="width:150px"> <%= link_to 'Edit order', edit_order_path(order) %> </li>
              <%= link_to "Leave a review", "/products/#{order.product.id}", {:class => "btn-outline-secondary ml-2"} %>
            </ul>
          <%end%>
        <% end %>
      <%end%>
    </div>
    <br>
    <div style="width:100%;background:#367978;padding:10px;border-top-left-radius:15px;border-bottom-left-radius:15px;">
      <h1 style=color:white;>Your listings:</h1>
    </div>
    <br>
    <div class="container-suborders ml-5">
      <%if Product.where(user_id: current_user.id) == []%>
        <br>
        <br>
        <%="You have no active listings. Add a listing here:"%><%= link_to "/products/new", {:class => "btn-outline-secondary ml-2"} do  %><button class=btn-main>Add listing</button><%end%>
        <br>
        <br>
        <br>
      <%else%>
        <% Product.all.each do |product| %>
          <%if current_user.id == product.user_id%>
            <h3 style="color:black"><%= link_to "#{product.name}", "/products/#{product.id}", {:class => "text-dark btn-light p-3 rounded-pill"} %></h3>
            <br>
            <ul style="list-style: none">
              <li><h3>  </h3> </li>
              <li><strong>In stock: </strong><%= "#{product.stock_info} #{product.unit}" %> </li>
              <li><strong>Description: </strong> <%= "#{product.description}" %> </li>
              <li class=btn-main style="width:150px"> <%= link_to 'Edit listing', edit_product_path(product) %> </li>
            </ul>
          <%end%>
        <% end %>
      <%end%>
    </div>
    <br>
    <div>
      <div style="width:100%;background:#367978;padding:10px;border-top-left-radius:15px;border-bottom-left-radius:15px;">
        <h1 style=color:white>Sold offers:</h1>
      </div>
      <br>
      <div class="container-suborders ml-5">
        <% @orders.each do |order| %>
          <%if current_user.id == order.product.user.id%>
            <h3 class="text-dark"> <%= "#{order.product.name}" %></h3>
            <p> <%=  "Order contains:" %> </p>
            <ul style="list-style: none">
              <li> <strong>Order id: </strong> <%="#{order.id}" %> </li>
              <li> <strong>Amount: </strong><%= "#{order.quantity} #{order.product.unit}" %> </li>
              <li> <strong>Description: </strong> <%= "#{order.product.description}" %> </li>
            </ul>
          <%end%>
        <% end %>
      </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

    <div>
      Thank you for using Farmer's market.
      <%= link_to "back to front page", "/products", {:class => "btn-outline-secondary ml-2"} %>
    </div>
  </div>

app/views/orders/new.html.erb
<div class="container">
  <h1>Add a new Order</h1>
  <div class="product-wrapper">

    <%= simple_form_for [@product, @order] do |f| %>
    <p>Enter the quantity you want to add:</p>
   
    <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/orders/personal_index.html.erb
<h1>Your Offers:</h1>
<body>
  <div class="container">
    <% @orders.each do |order| %>
      <%if current_user.id == order.product.user.id%>
        <h1>YESSS</h1>
      <%end%>
    
    <% end %>
  </div>
  <div>
    Thank you for ordering at the Farmers market.
    <%= link_to "back to front page", "/products", {:class => "btn-outline-secondary ml-2"} %>
  </div>
</body>

app/views/pages/home.html.erb
<div class="wrapper">
  <div class="container">
    <div class="flex-hero" >
      <div class="hero-header">
        <h1>A beautiful meal is a work of heart</h1>
        <br>
        <p class="value-prop"> Get your veggies from a local farm around you. And share what you've grown with people!</p><br>
        <% if user_signed_in? %>
        <%= link_to "Get Involved", "/products", class: "btn-big-home" %>
        <% else %>
        <p><%= link_to "Get Involved", "/users/sign_up", class: "btn-big-home" %></p>
        <% end %>
      </div>
      <%=image_tag("farmdrawing.jpg", class: "home-drawing") %>
    </div>
    <section>
      <h2 class="cool-quote"> "Choosing to purchase locally grown food is an important way to support your local economy, contribute to your community, improve your health and do your part to protect the environment. Getting involved in the local food system helps us to gain back the separation we created between humans and food production."
      </h2>
      <%=image_tag("farmphotos2.jpg", style: "width:100%; margin-top:120px 0;") %>
      <div class="disp-flex">

        <div>
          <h2 id="about" style="margin-top:80px;">A safer food supply</h2>
          <p class="value-prop">The more steps there are between you and your food’s source the more chances there are for contamination. Food grown in distant locations has the potential for food safety issues at harvesting, washing, shipping and distribution.</p>
        </div>

        <div>
          <h2 style="margin-top:160px;">We see the opportunity to make a difference</h2>
          <p class="value-prop">The money that is spent with local farmers and growers all stays close to home and is reinvested with businesses and services in your community.</p>
        </div>
      </div>
      <div class="center">

        <p style="margin: 80px 0;"><%= link_to "See Products", "/products", class: "btn-big-2 center" %></p>
      </div>
    </section>
  </div>
</div>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/edit.html.erb
<h1>Edit your listing:</h1>

<div class=wrapper>
  <%=image_tag("carrothead.jpg", class: "top-bg") %>
  <div class="container">
  <h2 style="margin-top: 16px;">List your product</h2>
  <p>Your item will become available whenever you create it.</p>
    <%= simple_form_for [ @product ] do |f| %>
        <%= f.input :name, input_html: { class: "form-inpt"} %>
        <%= f.input :description, input_html: { class: "form-inpt"} %>
        <%= f.association :category, input_html: { class: "form-inpt"} %>
        <%= f.input :unit, input_html: { class: "form-inpt"} %>
        <%= f.input :stock_info, label: "In stock", input_html: { class: "form-inpt", min: 0 } %>
        <%= f.input :price, input_html: { class: "form-inpt"} %>
        <%= f.input :photos, as: :file,  input_html: { multiple: true }%>
        <%= f.submit "List Item", class: "btn-main" %>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<div class=wrapper>
  <%=image_tag("carrothead.jpg", class: "top-bg") %>
  <div class="container">
    <div class="search-section">
      <div class="search-bg">
        <%= form_tag products_path, method: :get, wrapper_html: {class: "form-inline"} do %>
        <%= text_field_tag :query,
        params[:query],
        class: "farm-search",
          placeholder: "Search for a product or a category"%>
          <%= submit_tag "Search", class: "btn-main" %>
          <% end %>
        </div>
      </div>
      <br>
      <div class="wide-head">
        <% if params[:query] == nil %>
        <h2 class= "searched">All Products</h2>
        <% else %>
        <h2 class= "searched">Search Results for: <i><%= params[:query] %></i> </h2>
        <% end %>
        <p><i>You can use the search bar to narrow down the product list!</i></p>
      </div>
      <div class="cards">
        <% @products.each do |product | %>
        <div class="card-category"> <%= link_to "products/#{product.id}" do %>
          <div class="outer-card">
            <div class="big-card">
              <img src="<%= cl_image_path product.photos.first.key %>" class= "card-img">
            </div>
          </div>
          <h3 class="card-info cardtext1" style="margin-top: 16px;"> <%= product.name%></h3>
          <h3 class="card-info" style="font-weight: 600; color: rgba(0, 0, 0, 0.4);"> <%= product.user.first_name%></h3>
          <h3 class="card-info" data-hover="Add to cart" style="font-weight: 600; color: rgba(0, 0, 0, 1); margin-top: 8px;"> <%= number_to_currency(product.price, :unit => "€")%></h3>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/products/new.html.erb
<div class=wrapper>
  <%=image_tag("carrothead.jpg", class: "top-bg") %>
  <div class="container">
  <h2 style="margin-top: 16px;">List your product</h2>
  <p>Your item will become available whenever you create it.</p>
    <%= simple_form_for [ @product ] do |f| %>
        <%= f.input :name, input_html: { class: "form-inpt"} %>
        <%= f.input :description, input_html: { class: "form-inpt"} %>
        <%= f.association :category, input_html: { class: "form-inpt"} %>
        <%= f.input :unit, input_html: { class: "form-inpt"} %>
        <%= f.input :stock_info, label: "In stock", input_html: { class: "form-inpt", min: 0 } %>
        <%= f.input :price, input_html: { class: "form-inpt"} %>
        <%= f.input :photos, as: :file,  input_html: { multiple: true }%>
        <%= f.submit "List Item", class: "btn-main" %>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<script>
function myFunction(imgs) {
  var expandImg = document.getElementById("expandedImg");
  expandImg.src = imgs.src;
}
</script>

<div class=wrapper>
  <%=image_tag("carrothead.jpg", class: "top-bg") %>
  <div class="container" style="height: 150vh;">
   <h1 style="margin-top: 16px;">Product Detail Page</h1>
   <div class="product-wrapper">
    <div class="gallery">
      <div class="thumb-row">
      <% @product.photos.each do |photo| %>
      <div class="column">
      <img src='<%= cl_image_path photo.key, height: 300, width: 400, crop: :fill %>' onclick=myFunction(this)>
      </div>
      <% end %>
      </div>
      <div class="gallery-big-img">
        <img id="expandedImg" src="<%= cl_image_path @product.photos.first.key %>">
      </div>
    </div>
    <div class="card-info" style="text-align:left;">
      <h3><%=@product.name%></h3>
      <h4><%= @product.user.first_name %></h4>
      <p class= "desc-text" style="text-align:left;"><%= @product.description %></p>
      <p class= "desc-text" style="text-align:left;">Recyclebale packaging will be prepared before pick up.</p>
      <p class="price" style="text-align:left;">Price: <%= number_to_currency(@product.price, :unit => "€")%> </p>
      <p style="font-size: 14px; text-align:left;">Available Amount: <%= @product.stock_info%> </p>

        <div class="product-wrapper" style="text-align:left;">
          <%= simple_form_for([@product, @order]) do |f| %>
          <p class= "desc-text" style="text-align:left;">Enter the quantity you want to add:</p>
          <%= f.input :quantity, input_html: { min: 0, style: "width: 120px;", value: "1" } %>
          <%= f.button :submit, class: "btn btn-main" %>
          <% end %>

        </div>
        <div class="container">
      </div>
    </div>
  </div>
        <div>
          <h2>Leave a review</h2>
          <%= simple_form_for [ @product, @review ] do |f| %>
            <%= f.input :content %>
            <%= f.submit "Submit review", class: "btn btn-main" %>
          <% end %>
          </div>
          <br>
          <br>
          <h2>Reviews:</h2>
          <ul style="list-style: none">
          <% @product.reviews.each do |review| %>
            <div style ="border:1px solid #B8B8B8;padding: 8px;margin-top: 8px">
              <%if review.product.buyers.include? review.user_id %>
                <p style="text-align:right; color:#006600; display:inline ">Verified purchase &nbsp;&nbsp</p>
              <%end%>
              <h5 style="display:inline"><strong><%=current_user.first_name%></strong><p style="display:inline"> said:</p>
              <br>
              <br>
            <p> <%= "#{review.content}" %> </p>
            </div>
          <%end%>
          </ul>
        </div>

app/views/reviews/new.html.erb
<!-- app/views/reviews/new.html.erb -->
<%= simple_form_for [ @product, @review ] do |f| %>
  <%= f.input :content %>
  
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
<div class="alert alert-info alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= notice %>
</div>
<% end %>
<% if alert %>
<div class="alert alert-warning alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= alert %>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="foot">
  <div class="footer-box">
    <p>Farmer's Market © 2020</p>
    <ul class="social-icons">
      <li><i class="fab fa-facebook-f"></i></li>
      <li><i class="fab fa-twitter"></i></li>
      <li><i class="fab fa-instagram"></i></li>
    </ul>
  </div>


</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
  <%= image_tag "logo.png", class: "avatar" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to "Home", "/", class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "About Us", "/#about", class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Products", "/products", class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <i class=nav-link style="font-style:normal"><%= "#{current_user.first_name}" %></i>
      </li>
      <li class="nav-item dropdown">
        <%if current_user.photo.attached?%>
        <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle",  id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <%else%>
        <%= image_tag "https://envato-shoebox-0.imgix.net/d758/4303-6568-4778-9d91-de421163e388/Asparagus-13+copy.jpg?auto=compress%2Cformat&fit=max&mark=https%3A%2F%2Felements-assets.envato.com%2Fstatic%2Fwatermark2.png&markalign=center%2Cmiddle&markalpha=18&w=500&s=c050a58498886415f5cb99cf7fec0b3b", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <%end%>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Dashboard", "/orders", class: "dropdown-item" %>
          <%= link_to "Add listing", "/products/new", class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
      <li class="nav-item active">
        <%= link_to "Products", "/products", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>